// Generated by CoffeeScript 1.6.3
(function() {
  var AmorphousRecipe, CraftingThesaurus, ItemPile, PositionalRecipe, Recipe, RecipeLocator, ToolsPlugin, _ref;

  ItemPile = require('itempile');

  _ref = require('craftingrecipes'), Recipe = _ref.Recipe, AmorphousRecipe = _ref.AmorphousRecipe, PositionalRecipe = _ref.PositionalRecipe, CraftingThesaurus = _ref.CraftingThesaurus, RecipeLocator = _ref.RecipeLocator;

  module.exports = function(game, opts) {
    return new ToolsPlugin(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['craftingrecipes', 'voxel-registry']
  };

  ToolsPlugin = (function() {
    function ToolsPlugin(game, opts) {
      var _ref1;
      this.game = game;
      this.registry = (function() {
        var _ref2;
        if ((_ref1 = (_ref2 = game.plugins) != null ? _ref2.get('voxel-registry') : void 0) != null) {
          return _ref1;
        } else {
          throw 'voxel-pickaxe requires "voxel-registry" plugin';
        }
      })();
      this.enable();
    }

    ToolsPlugin.prototype.enable = function() {
      var recipes, _ref1;
      this.registry.registerBlock('plankOak', {
        texture: 'planks_oak'
      });
      this.registry.registerItem('pickaxeWood', {
        itemTexture: '../items/wood_pickaxe',
        speed: 2.0
      });
      this.registry.registerItem('pickaxeStone', {
        itemTexture: '../items/stone_pickaxe',
        speed: 10.0
      });
      this.registry.registerItem('stick', {
        itemTexture: '../items/stick'
      });
      recipes = (_ref1 = this.game.plugins) != null ? _ref1.get('craftingrecipes') : void 0;
      if (recipes != null) {
        recipes.thesaurus.registerName('wood.plank', 'plankOak');
        recipes.register(new AmorphousRecipe(['wood.log'], new ItemPile('plankOak', 2)));
        recipes.register(new AmorphousRecipe(['wood.plank', 'wood.plank'], new ItemPile('stick', 4)));
        recipes.register(new PositionalRecipe([['wood.plank', 'wood.plank', 'wood.plank'], [void 0, 'stick', void 0], [void 0, 'stick', void 0]], new ItemPile('pickaxeWood', 1)));
        return recipes.register(new PositionalRecipe([['cobblestone', 'cobblestone', 'cobblestone'], [void 0, 'stick', void 0], [void 0, 'stick', void 0]], new ItemPile('pickaxeStone', 1)));
      }
    };

    ToolsPlugin.prototype.disable = function() {};

    return ToolsPlugin;

  })();

}).call(this);
